// The author disclaims copyright to this document.
:toc:
:toc-title: Table of contents
:toclevels: 5
:sectnums:
:hide-uri-scheme:

= Kweker (Grower)

As useful as windshield wipers on a goat's ass.

== Environment

Typical environment for growing cannabis.

=== Temperature

.Temperature
[%autowidth]
|===
| environment| min.[°C] | max.[°C] | description        
                                                        
| day        | 25       | 30       | allowed higher     
| night      | 15       | 20       | not allowed lower  
| day-night  |          | 10       | difference at most 
|===

=== Humidity

.Humidity
[%autowidth]
|===
| environment | min.[%RH] | max.[%RH] | description
                                        
| sprout      | 70        | 80        | higher
| vegetative  | 40        | 70        | normal          
| bloom       | 20        | 40        | lower
|===

=== CO2 concentration

.CO2 concentration
[%autowidth]
|===
| environment          | min. [ppm] | max. [ppm] | description  
                                                           
| outdoor              |   250 | 400  | background (normal) outdoor air level.footnote:dhs[https://www.dhs.wisconsin.gov/chemical/carbondioxide.htm]
| good                 |   400 | 1000 | typical level found in occupied spaces with good air exchange.footnote:dhs[]
| enriched vegetative  |   800 | 1200 | enriched vegetative towards lower end
| enriched bloom       |   800 | 1200 | enriched bloom towards higher end
| poor                 |  1000 | 1200 | level associated with complaints of drowsiness and poor air.footnote:dhs[]
| stuffy               |  2000 | 5000 | level associated with headaches, sleepiness, and stagnant, stale, stuffy air. Poor concentration, loss of attention, increased heart rate and slight nausea may also be present.footnote:dhs[]
| toxic                |  5000 |      | this indicates unusual air conditions where high levels of other gases could also be present. Toxicity or oxygen deprivation could occur. This is the permissible exposure limit for daily workplace exposures.footnote:dhs[]
| immediately harmful  | 40000 |      | this level is immediately harmful due to oxygen deprivation.footnote:source
|===

=== Cause and effect

How a positive increase in one phenomenon affects another.

* (+) causes an increase
* (-) causes a decrease
* effect depends on environment

.Cause and effect
[%autowidth]
|===
|Cause/Effect             |Temperature    | Relative Humidity | CO2 concentration

|Ambient temperature      |+              |-              |            
|Ambient humidity         |               |+              |             
|Ambient CO2 concentration|               |               |+             
|Light on                 |+              |-              |- (more photosynthesis)            
|Exhaust fan              |towards ambient|towards ambient|towards ambient            
|Recirculation fan        |               |               |            
|Heater                   |+              |-              |            
|===

== Model

.Model
|===
| Name | Data type

2+| Current state
| Control mode | control mode
| Time | time
| Circadian | circadian
| Temperature | temperature
| Humidity | humidity
| CO2 concentration | CO2 concentration

2+| Actuator state
| Light switch state | switch state
| Heater switch state | switch state
| Exhaust fan switch state | switch state
| Recirculation fan switch state | switch state

2+| Automatic control 
| Begin of day time setpoint | Time
| Begin of night time setpoint | Time
| Day temperature setpoint | Temperature
| Day humidity setpoint |  Humidity
| Day CO2 concentration setpoint | CO2 concentration
| Night temperature setpoint | Temperature
| Night humidity setpoint | Humidity
| Night CO2 concentration setpoint | CO2 concentration
| Temperature control level | Control level
| Humidity control level | Control level
| CO2 concentration control level | Control level

2+| Manual control
| Light switch setpoint | Temperature
| Heater switch setpoint | Temperature
| Exhaust fan switch setpoint | Temperature
| Recirculation fan switch setpoint | Temperature
|===

.Data types
|===
| Data type | Range | Unit

| Time | 00:00..23:59 |
| Circadian | day, night |
| Temperature | 0.0 .. 50.0 | C
| Humidity | 0.0 .. 100.0 | %RH
| CO2 concentration | 0 .. 2000 | ppm
| Switch state | on, off |
| Control mode | off, manual, automatic |
| Control level | low, normal, high |
|===

== Boundaries

=== Sensors

.Sensors
|===
| Name

| Clock
| Temperature
| Humidity
| CO2 concentration
|===

=== Actuators

.Actuators
|===
| Name

| Light
| Heater
| Exhaust fan
| Recirculation fan
|===

=== Human machine interface

.Human machine interface
|===
| Group | Content | Editable

3+| *Common*
.8+| *Toolbar*
| Time |
| Control... |
| Settings... |
| About... |
| Light switch state |
| Heater switch state |
| Exhaust fan switch state |
| Recirculation fan switch state |
3+| *Control*
.1+| *General*
| Control mode |
.3+| *Measurements*
| Temperature |
| Humidity |
| CO2 concentration |
.3+| *Setpoints*
| Temperature |
| Humidity |
| CO2 concentration |
.3+| *Control*
| Temperature control levels |
| Humidity control levels |
| CO2 concentration control levels |
.4+| *Output*
| Light switch state | Y(manual)
| Heater switch state | Y(manual)
| Exhaust fan switch state | Y(manual)
| Recirculation fan switch state | Y(manual)

3+| *Settings*
.1+| *General*
| Time | Y
.8+| *Control automatic*
| Begin of day time setpoint | Y
| Begin of night time setpoint | Y
| Day temperature setpoint | Y
| Day humidity setpoint | Y
| Day CO2 concentration setpoint | Y
| Night temperature setpoint | Y
| Night humidity setpoint | Y
| Night CO2 concentration setpoint | Y

3+| *About*
.2+| *Text*
| Product description |
| Other product licenses |

|===

.Control
[ditaa]
....
              +-------------+ ------------+ ------------+      
  12:34       |  Control    |  Settings   |  About      | (L)(H)(E)(R)
+-------------+             +-------------+-------------+-------------+
|                                                                     |
|    T [C]    |    RH [%]   |  CO2 [ppm]  |  MODE       |  OUTPUT     |
|             |             |             | +---------+ | +---------+ | 
|     (H)     |     (H)     |     (H)     | | OFF     | | | LIGHT   | |
|             |             |             | +---------+ | +---------+ |
|             |             |             |             |             |
|             |             |             | +---------+ | +---------+ |
|     23      |      42     |     612     | | MANUAL  | | | HEATER  | |
|             |             |             | +---------+ | +---------+ |
|             |             |             |             |             |
|             |             |             | +---------+ | +---------+ |
|     (L)     |     (L)     |     (L)     | | AUTO    | | | EXHAUST | |
|             |             |             | +---------+ | +---------+ |
|             |             |             |             |             |
|             |             |             |             | +---------+ |
|     24      |     35      |     800     |             | | RECIRC. | |
|             |             |             |             | +---------+ |
+---------------------------------------------------------------------+
....

.Settings
[ditaa]
....
              + ------------+-------------+ ------------+             
  12:34       |  Control    |  Settings   |  About      | (L)(H)(E)(R)          
+-------------+-------------+             +-------------+-------------+
|                                                                     |
| Time                                  |                   - 12:34 + |
|                                       |                             |
| Begin of day time                     |                   - 06:00 + |
|                                       |                             |
| Begin of night time                   |                   - 22:00 + |
|                                       |                             |
| Day temperature                       |                   -   28  + |
|                                       |                             |
| Day humidity                          |                   -   35  + |
|                                       |                             |
| Day CO2 concentration                 |                   -  800  + |
|                                       |                             |
| Night temperature                     |                   -   18  + |
|                                       |                             |
| Night humidity                        |                   -   35  + |
|                                       |                             |
| Night CO2 concentration               |                   -  400  + |
+---------------------------------------------------------------------+
....

.About
[ditaa]
....
              + ------------+ ------------+-------------+
  12:34       |  Control    |  Settings   |  About      | (L)(H)(E)(R)
+-------------+-------------+-------------+             +-------------+
|                                                                     |
| Product description                                                 | 
| ..                                                                  |
|                                                                     |
| 3rd party licenses                                                  |
| ..                                                                  |
|                                                                     |
|                                                                     |
|                                                                     |
|                                                                     |
|                                                                     |
|                                                                     |
|                                                                     |
|                                                                     |
|                                                                     |
|                                                                     |
+---------------------------------------------------------------------+
....


== Control

=== Light

The light is not a means of control. It is strictly following the night/day circadian rhythm that was set.
The heat of the light does have an effect on temperature and thus humidity of the environment. 

.Cause and effect
* ON
    ** Increase temperature
    ** Decrease relative humidity (higher temperature)
    ** Increase relative humidity (more evaporation)
    ** Reduce CO2 concentration (photosynthesis)
* OFF
    ** Decrease temperature
    ** Increase relative humidity (lower temperature)
    ** Decrease relative humidity (less evaporation)

.Light control
|===
| Condition | Result

2+| *control off*
2+| *control manual*
2+| *control automatic*

| circadian day | ON
| circadian night | OFF
|===

=== Exhaust fan

Reduces the humidity (produced by evaporation through leaves) to avoid mold.
Follows the ambient temperature, humidity, and CO2 concentration.

.Cause and effect
* ON
    ** Follow ambient temperature
    ** Follow ambient humidity
    ** Follow ambient CO2 concentration
* OFF
    ** Increase temperature (if light is on, producing heat)
    ** Increase humidity (evaporation)
    ** Reduce CO2 concentration (if light is on, photosynthesis)

.Exhaust fan control
[%autowidth]
|===
| Condition | Result

| Temperature high | ON
| Temperature low | OFF
| Humidity high | ON
| Humidity low | OFF
| CO2 concentration high | ON
| else | OFF
|===

=== Recirculation fan

.Cause and effect
* ON
    ** Promote stirdy stem growth
    ** Promote nutrient transport by promoting evaporation
    ** Plant produces more flowers where wind blows
    ** Disperse CO2 that is needed on the leaves, not on the ground
    ** Equalize temperature
* OFF
    ** No energy use

.Recirculation fan control
[%autowidth]
|===
| condition | result

2+| *control off*
2+| *control manual*
2+| *control automatic*

| circadian day | ON
| circadian night | OFF |           
|===

=== Heater

Avoid low temperature, and avoid mold.

** list: Cause and effect **

* ON
    ** Increase temperature
    ** Decrease relative humidity
* OFF
    ** Decrease temperature
    ** Increase relative humidity

.Heater control
[%autowidth]
|===
| condition | result

2+| *control off*
2+| *control manual*
2+| *control automatic*

| temperature high | OFF
| temperature low | ON
| humidity high | ON
| else | OFF
|===


// external level 2 sections
include::controller.adoc[]
include::../components/am2301/AM2301.adoc[]
include::../components/mhz19b/MH-Z19B.adoc[]
include::HDR-60-5.adoc[]
include::SSR-10-DA.adoc[]
include::layout.adoc[]
include::mains_wiring.adoc[]
include::control_wiring.adoc[]