// The author disclaims copyright to this document.
=== Interface

The bus signal is a single wire shared for in- and output by both the host and the device.
Both parties use open-drain type outputs to pull-down the signal from the floating (pulled-high) signal level.

* Phase 1: Host start
** Host pulls the signal low (Tbe)
** Host floats the signal high
* Phase 2: device response
** Device pulls the signal low (Trel)    
** Device floats the signal high (Treh)
* Phase 3: device exchanges bits (40x)
** Device pulls the signal low (Tlow)
** Device floats the signal high  (Thi0, or Thi1)
** Bit is interpreted as low (0) when Thi < Tlow
** Bit is interpreted as high (1) when Thi > Tlow
* Phase 4: device release
** Device drives the signal high  (Thi0, or Thi1)


[ditaa]
....
             Tgo      Treh       Thi0      Thi1                  Thi0
 ---+       +---+    +----+     +---+     +-------+       +     +---+   +---
    |       |   |    |    |     |   |     |       | . . . |     |   |   |
    +-------+   +----+    +-----+   +-----+       +       +-----+   +---+
     Tbe         Trel      Tlow      Tlow                  Tlow      Ten

                          |<------->|<----------->|  . . .|<------->|

                           bit39 (0) bit38 (1)             bit0 (0)

    |<--------->|<------->|<--------------------------------------->|<-->|                       

       phase 1    phase 2   phase 3 (40 bits)                        phase 4

....

.Interface characteristics
[%autowidth]
|===
| symbol | parameter | min | typ | max | unit

| Tbe  | Host start pull low       | 0.8 | 1  | 20  | ms
| Tgo  | Host float high           | 20  | 30 | 200 | μs
| Trel | Device start pull low     | 75  | 80 | 85  | μs
| Treh | Device float high         | 75  | 80 | 85  | μs
| Tlow | Device data low time      | 48  | 50 | 55  | μs
| Thi0 | Device data "0" high time | 22  | 26 | 30  | μs
| Thi1 | Device data "1" high time | 68  | 70 | 75  | μs
| Ten  | Device release            | 45  | 50 | 55  | μs
|===


=== Software decoding

This software decodes the incoming signal using the following state model.

[plantuml,States,format=png]
....
@startuml

state BUSY  {
	HOST_SEND_START : -> host send start
	WAIT_FOR_DEVICE_START :
	WAIT_FOR_DEVICE_DATA_LOW :
	WAIT_FOR_DEVICE_DATA_HIGH :
	WAIT_FOR_DEVICE_RELEASE :
	HOST_BUS_FLOAT : 
	WAIT_FOR_DEVICE_RATE_LIMIT :
	RECOVERABLE :
}

[*] --> COMPONENT_UNINITIALIZED
COMPONENT_UNINITIALIZED --> COMPONENT_READY : setup ok
COMPONENT_UNINITIALIZED --> COMPONENT_FATAL : setup fail
COMPONENT_READY -> HOST_SEND_START : measure
HOST_SEND_START --> WAIT_FOR_DEVICE_START : always
WAIT_FOR_DEVICE_START --> WAIT_FOR_DEVICE_DATA_LOW : high
WAIT_FOR_DEVICE_START --> WAIT_FOR_DEVICE_START : low
WAIT_FOR_DEVICE_DATA_LOW --> WAIT_FOR_DEVICE_DATA_HIGH : low & (bit <> 0)
WAIT_FOR_DEVICE_DATA_LOW --> WAIT_FOR_DEVICE_RELEASE : low & (bit == 0)
WAIT_FOR_DEVICE_DATA_HIGH --> WAIT_FOR_DEVICE_DATA_LOW : high
WAIT_FOR_DEVICE_RELEASE --> RECOVERABLE : low -> host bus float
WAIT_FOR_DEVICE_RELEASE --> HOST_BUS_FLOAT : high -> host bus float
HOST_BUS_FLOAT --> WAIT_FOR_DEVICE_RATE_LIMIT : high
HOST_BUS_FLOAT --> RECOVERABLE : low
WAIT_FOR_DEVICE_RATE_LIMIT --> COMPONENT_READY : device hold-off expired
RECOVERABLE --> COMPONENT_READY : device hold-off expired
COMPONENT_FATAL --> [*]

@endum
....
