@startuml

state PROCESS_EDGE {
	[*] --> HOST_START
	BUS_IDLE : Bus idle
	HOST_START : Host send start
	WAIT_START_LOW : Wait for device start low
	WAIT_START_HIGH : Wait for device start  High
	WAIT_DATA_LOW : Wait for device data low
	WAIT_DATA_HIGH : Wait for device data high
	WAIT_RELEASE : Wait for device release
	BUS_ERROR : Bus Error
}

state PROCESS_INSTRUCTION {
	WAIT_DEVICE_INTERVAL : Wait for device minimum interval
}

WAIT_DEVICE_INTERVAL --> PROCESS_EDGE : start
WAIT_DEVICE_INTERVAL -> WAIT_DEVICE_INTERVAL : wait

HOST_START --> WAIT_START_LOW
WAIT_START_LOW --> WAIT_START_HIGH : low
WAIT_START_LOW -> WAIT_START_LOW : high
WAIT_START_HIGH --> BUS_ERROR : low
WAIT_START_HIGH --> WAIT_DATA_LOW : high
WAIT_DATA_LOW --> WAIT_DATA_HIGH : low (bit <> 0)
WAIT_DATA_LOW --> WAIT_RELEASE : low (bit == 0)
WAIT_DATA_HIGH --> WAIT_DATA_LOW : high
WAIT_RELEASE --> BUS_ERROR : low
WAIT_RELEASE --> BUS_IDLE : high

@endum
